CHAMPS_A_EXTRAIRE = [
    "qte",
    "prix",
    "total",
    "nom_destinataire",
    "prix_unitaire_ht",
    "total_ht",
]

CHAMPS_OBLIGATOIRES = [
    "nom_destinataire",
    "total_ht",
]

COLONNES_EXPORT = [
    "nom_destinataire",
    "qte",
    "prix",
    "prix_unitaire_ht",
    "total",
    "total_ht",
]

DATA_SUBDIRECTORIES = [
    "uploads",
    "rendered_pages",
    "processed",
    "extracted_json",
    "exports",
    "temp",
    "logs",
]

MOTS_CLES_MONTANTS = {
    "qte": [
        "qte",
        "qté",
        "quantite",
        "quantité",
        "qty",
        "quantity",
        "nombre",
        "nb",
        "nbr",
        "nbe",
        "nbre",
        "nbre.",
        "nombre d'articles",
        "nombre articles",
        "nombre de pièces",
        "nombre de pieces",
        "pièces",
        "pieces",
        "pcs",
        "pc",
        "unité",
        "unite",
        "unités",
        "unites",
        "u",
        "q.",
        "qt.",
        "q.té",
        "qte.",
        "qté.",
    ],

    "prix": [
        "prix",
        "price",
        "montant",
        "amount",
        "tarif",
        "coût",
        "cout",
        "valeur",
        "val.",
        "prix ht",
        "prix ttc",
        "montant ht",
        "montant ttc",
        "prix total",
        "total prix",
        "prix net",
        "net",
        "pu",
        "p.u",
        "p u",
        "p/u",
        "p.u.",
    ],

    "prix_unitaire_ht": [
        "prix unitaire ht",
        "prix unitaire h.t",
        "prix unitaire h.t.",
        "prix unité ht",
        "prix unite ht",
        "prix d'unité ht",
        "prix d unite ht",
        "prix par unité ht",
        "prix par unite ht",
        "prix/u ht",
        "prix / u ht",
        "prix/unit ht",
        "prix / unit ht",
        "prix / unité ht",
        "prix / unite ht",
        "p.u ht",
        "p.u. ht",
        "pu ht",
        "p u ht",
        "p/u ht",
        "p.u.h.t",
        "pu h.t",
        "pu h.t.",
        "prix unit ht",
        "prix unit. ht",
        "prix unitaire hors taxe",
        "prix unitaire hors taxes",
        "prix unite hors taxe",
        "prix unite hors taxes",
        "prix unité hors taxe",
        "prix unité hors taxes",
        "prix ht unitaire",
        "prix ht/u",
        "prix ht / u",
        "unit price excl tax",
        "unit price ht",
        "unit price excluding tax",
        "unit price before tax",
    ],

    "total": [
        "total",
        "totale",
        "montant total",
        "total montant",
        "somme",
        "sous total",
        "sous-total",
        "subtotal",
        "sub total",
        "montant",
        "amount",
        "total ligne",
        "total de ligne",
        "montant ligne",
        "montant de ligne",
        "ligne total",
        "line total",
        "total article",
        "total produit",
        "total service",
        "prix total",
        "total prix",
        "net à payer",
        "net a payer",
        "à payer",
        "a payer",
        "total à payer",
        "total a payer",
        "total général",
        "total general",
    ],

    "total_ht": [
        "total ht",
        "total h.t",
        "total h.t.",
        "total hors taxe",
        "total hors taxes",
        "montant ht",
        "montant h.t",
        "montant h.t.",
        "montant hors taxe",
        "montant hors taxes",
        "sous total ht",
        "sous-total ht",
        "subtotal ht",
        "total net ht",
        "net ht",
        "net hors taxe",
        "net hors taxes",
        "base ht",
        "base hors taxe",
        "base hors taxes",
        "total avant taxe",
        "total avant taxes",
        "total avant tva",
        "montant avant taxe",
        "montant avant taxes",
        "montant avant tva",
        "total excl tax",
        "total excluding tax",
        "amount excl tax",
        "amount excluding tax",
        "total before tax",
        "subtotal before tax",
        "ht",
        "h.t",
        "h.t.",
    ],
}

MOTS_CLES_DESTINATAIRE = [
    "destinataire",
    "client",
    "nom destinataire",
    "nom du destinataire",
    "nom client",
    "nom du client",
    "raison sociale client",
    "société cliente",
    "societe cliente",
    "entreprise cliente",
    "acheteur",
    "buyer",
    "customer",
    "customer name",
    "bill to",
    "billed to",
    "facturé à",
    "facture à",
    "facture a",
    "facturé a",
    "adressé à",
    "adresse à",
    "adresse a",
    "livré à",
    "livre a",
    "ship to",
    "sold to",
    "à l'attention de",
    "a l'attention de",
    "attn",
    "attention",
    "monsieur",
    "madame",
    "m.",
    "mme",
    "mr",
    "mrs",
]

DEVISE_DIRHAM = [
    "mad",
    "dh",
    "dhs",
    "dh.",
    "dhs.",
    "dirham",
    "dirhams",
    "د.م",
    "درهم",
    "دراهم",
]

MOTS_IGNORES_DESTINATAIRE = {
    "facture",
    "invoice",
    "date",
    "échéance",
    "echeance",
    "total",
    "total ht",
    "total ttc",
    "ttc",
    "tva",
    "ht",
    "qte",
    "qté",
    "quantite",
    "quantité",
    "prix",
    "prix unitaire",
    "prix unitaire ht",
    "montant",
    "page",
    "adresse",
    "telephone",
    "téléphone",
    "email",
    "ice",
    "if",
    "rc",
    "patente",
    "cnss",
    "description",
    "designation",
    "désignation",
    "référence",
    "reference",
}

COLONNES_AUDIT = [
    "nom_fichier",
    "numero_page",
    "confiance_ocr",
    "statut",
    "notes",
]